// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metrics/webrequest.proto

package cn.bithon.rpc;

public final class Webrequest {
  private Webrequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_bithon_rpc_WebRequestMetrics_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_bithon_rpc_WebRequestMetrics_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\030metrics/webrequest.proto\022\rcn.bithon.rp" +
      "c\"\231\001\n\021WebRequestMetrics\022\013\n\003uri\030\002 \001(\t\022\024\n\014" +
      "costNanoTime\030\003 \001(\003\022\020\n\010requests\030\004 \001(\003\022\020\n\010" +
      "count4xx\030\006 \001(\003\022\020\n\010count5xx\030\007 \001(\003\022\024\n\014requ" +
      "estBytes\030\010 \001(\003\022\025\n\rresponseBytes\030\t \001(\003B\002P" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_cn_bithon_rpc_WebRequestMetrics_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_bithon_rpc_WebRequestMetrics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_bithon_rpc_WebRequestMetrics_descriptor,
        new String[] { "Uri", "CostNanoTime", "Requests", "Count4Xx", "Count5Xx", "RequestBytes", "ResponseBytes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
